//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18449
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
//using System;
//using UnityEngine;
//public class ComponentAccessor :MonoBehaviour
//{
//	private ComponentAccessor instance;
//	void Awake(){
//		if (GameObject.FindObjectOfType<ComponentAccessor> ()) {
//			Destroy (this);
//		}
//	}
//	public static ComponentAccessor Instance(){
//		get{
//			if(instance == null){
//				instance = (ComponentAccessor)FindObjectOfType(typeof(ComponentAccessor));
//				if(instance == null)
//				{
//					// 無かった
//				}
//			}
//			return instance;
//		}
//	}
//
//	protected void Awake()
//	{
//		CheckInstance ();
//	}
//
//	protected bool CheckInstance()
//	{
//		if (this == Instance){return true;}
//		Destroy (this);
//		return false;
//	}
//}
//
//public class SingletonTest : SingletonMonoBehaviour<SingletonTest>
//{
//
//}

